export enum Status {
    RECEBIDO = 'RECEBIDO',
    ENVIADO = 'ENVIADO',
    ENTREGUE = 'ENTREGUE',
    CANCELADO = 'CANCELADO',
    AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
    PAGAMENTO_APROVADO = 'PAGAMENTO_APROVADO',
    PAGAMENTO_REPROVADO = 'PAGAMENTO_REPROVADO',
    NF_EMITIDA = 'NF_EMITIDA',
    EM_SEPARACAO = 'EM_SEPARACAO',
    EM_TRANSPORTE = 'EM_TRANSPORTE',
    FINALIZADO = 'FINALIZADO',
}
